inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false # RSpec ... :facepalm:

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Style/GuardClause:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
